FROM tuwunel-base:latest as builder
RUN --mount=type=bind,src=./.docker-home,target=.docker-home,readonly=false \
--mount=type=bind,target=./target/,readonly=false \ 
cargo chef cook --profile "test" --target x86_64-unknown-linux-musl --recipe-path recipe.json
RUN --mount=type=bind,src=./.docker-home,target=.docker-home,readonly=false \
--mount=type=bind,target=./target/,readonly=false \ 
 cargo install --path ./src/main --profile "test"
 
FROM alpine:latest
COPY --from=builder /usr/local/cargo/bin/tuwunel /usr/local/bin/tuwunel
RUN useradd -r tuwunel
EXPOSE 8008 8448
USER tuwunel
WORKDIR /home/tuwunel/